vaadin/vaadin-rich-text-editor-flow

vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorTest.java

Fixes #9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/12)

Add sanitization functionality for htmlValue and unit tests for it

---

vaadin-rich-text-editor-flow/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/18)

Bump webjar of the wc

---

vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorTest.java

Fix #20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/23)

Check sanitisation

---

vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java

Fixes #10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/26)

Add links to the delta github docs

---

vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/examples/MainView.java
vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/examples/RichTextEditorInATemplate.java
vaadin-rich-text-editor-flow-integration-tests/src/main/webapp/frontend/src/rte-in-a-template.html
vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/test/AbstractParallelTest.java
vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/test/BasicUseIT.java

I guess there is no need to test element with Polymer Template as it has no use inside the component.
Fixes #17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/28)

Add test for binder and Polymer Template

---

vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/examples/MainView.java
vaadin-rich-text-editor-flow/pom.xml
vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/31)

Bump rte wc dependency to 1.0.0-alpha6

---

vaadin-rich-text-editor-flow/assembly/MANIFEST.mf
vaadin-rich-text-editor-flow/assembly/assembly.xml
vaadin-rich-text-editor-flow/pom.xml

Connects to https://github.com/vaadin/vaadin-rich-text-editor/issues/12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/32)

Add assembly and directory conf profile

---

vaadin-rich-text-editor-flow/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/33)

Bump rte wc to 1.0.0-beta2

---

vaadin-rich-text-editor-flow-integration-tests/pom.xml
vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/test/AbstractParallelTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/37)

Update saucelabs connect plugin

---

vaadin-rich-text-editor-flow/pom.xml

fixes https://github.com/vaadin/vaadin-rich-text-editor-flow/issues/35
fixes https://github.com/vaadin/components-team-tasks/issues/433
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/36)

Add OSGi metadata

---

pom.xml
vaadin-rich-text-editor-flow-demo/pom.xml
vaadin-rich-text-editor-flow-demo/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditorView.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/40)

Rename demo module

---

.travis.yml
pom.xml
vaadin-rich-text-editor-flow-demo/pom.xml
vaadin-rich-text-editor-flow-integration-tests/pom.xml
vaadin-rich-text-editor-flow/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/53)

Update dependencies for V14

---

vaadin-rich-text-editor-flow-integration-tests/pom-bower-mode.xml
vaadin-rich-text-editor-flow-integration-tests/pom.xml
vaadin-rich-text-editor-flow-testbench/pom.xml

Add specific dependency for other components TBElements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/54)

Remove vaadin-components-testbench

---

.travis.yml
pom.xml
vaadin-rich-text-editor-flow-demo/pom.xml
vaadin-rich-text-editor-flow-integration-tests/pom-bower-mode.xml
vaadin-rich-text-editor-flow-integration-tests/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/55)

Prepare for rc2

---

pom.xml
vaadin-rich-text-editor-flow/pom.xml
vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/GeneratedVaadinRichTextEditor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/56)

Bump web component dependency to 1.0.4

---

vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/61)

Fix JavaDoc error

---

vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/67)

Add check for null in htmlValue getter

---

vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java

Fixes #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/71)

Update docs for initial value set with the constructor

---

.gitignore
.travis.yml

Update gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/72)

Update to xenial and openjdk

---

vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java

Fixes #74
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/77)

docs: improve docs related to dealing with value

---

vaadin-rich-text-editor-flow/pom.xml
vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/GeneratedVaadinRichTextEditor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/79)

Update web component version to 1.1.1

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/81)

Update flow-component-base to 2.1.0

---

pom.xml
vaadin-rich-text-editor-flow-demo/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/83)

Fix configuration for release

---

pom.xml
vaadin-rich-text-editor-flow-demo/pom.xml
vaadin-rich-text-editor-flow-integration-tests/pom-bower-mode.xml
vaadin-rich-text-editor-flow-integration-tests/pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor-flow/84)

Use snapshots

---

vaadin-rich-text-editor-flow-demo/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditorView.java

This issue is for users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files

Adding missing method to Vaadin Rich Text Editor demos

---

pom.xml
vaadin-rich-text-editor-flow-demo/pom.xml
vaadin-rich-text-editor-flow-integration-tests/pom-bower-mode.xml
vaadin-rich-text-editor-flow-integration-tests/pom.xml
vaadin-rich-text-editor-flow-testbench/pom.xml
vaadin-rich-text-editor-flow/pom.xml
vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/GeneratedVaadinRichTextEditor.java

* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534

Bump versions for V14.3

---

vaadin-rich-text-editor-flow/pom.xml
vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/GeneratedVaadinRichTextEditor.java

This is a PR for `2.2` branch, Vaadin 14.3.

Update web component version to 1.2.1
